server:
  port: 8083
website:
  name: 网站名称
  domain: www.yujie.com
  msg: 我这是一个博客网站
spring:
  profiles:
    active: dev
  datasource:
    name: test
    url: jdbc:mysql://106.14.64.42:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Hrdsys106
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 106.14.64.42
    port: 6379
    password: dlam_liu
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 1000
    timeout: 50000
  logging:
    config: classpath:log4j2.xml
    level:
      cn.jay.repository: trace
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.model


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql